### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by maelle** [MangoTheCat/blog_rstats_gender#1]
Hi, I appreciate the intent behind this project but I'm not at ease with the idea of assigning a binary gender based on pictures. I am not great at explaining this but please see this discussion https://github.com/forwards/Archive that led to R Forwards deciding to only use survey data in the future, where respondents can use free text for their gender. Automatic gender recognition might hurt some people so I preferred opening this issue but please know that I appreciate your being interested in women representation.

**Comment by adfi** [comment]
Thanks for the feedback and also thanks for the reference, an interesting read (wish I had read it before). @hfrick pointed out the same thing but I should mention it more explicitly. I'll try to update the blog.

**Comment by maelle** [comment]
Awesome, thanks!
